### ISSUE TITLE
UMA Kovan subgraph failed at block 24.146.323

### ISSUE THREAD

**Issue by niklr** [UMAprotocol/subgraphs#15]
https://thegraph.com/explorer/subgraph/umaprotocol/uma-kovan

![grafik](https://user-images.githubusercontent.com/4712166/119625445-7b267380-be0a-11eb-9bf6-b7002125aed1.png)

**Comment by nicholaspai** [comment]
> https://thegraph.com/explorer/subgraph/umaprotocol/uma-kovan
> 
> 
> 
> ![grafik](https://user-images.githubusercontent.com/4712166/119625445-7b267380-be0a-11eb-9bf6-b7002125aed1.png)
> 
> 

This is a deprecated subgraph check out the new ones in the README
