### ISSUE TITLE
Whitelisted Tokens Missing from Mainnet Contracts Subgraph

### ISSUE THREAD

**Issue by AC-FTW** [UMAprotocol/subgraphs#6]
The mainnet contracts subgraph (https://api.thegraph.com/subgraphs/name/umaprotocol/mainnet-contracts) is not showing all the expected tokens that have been whitelisted in contract 0xdbf90434df0b98219f87d112f37d74b1d90758c7.

Examining the log events for contract 0xdbf90434df0b98219f87d112f37d74b1d90758c7 shows that there have been 29 AddedToWhitelist events:
![image](https://user-images.githubusercontent.com/16608312/113811634-d05ad880-9729-11eb-9186-7e688f9e47dd.png)

However, the current mainnet contracts subgraph only shows the following 10 that match the addresses in the whitelist events:
![image](https://user-images.githubusercontent.com/16608312/113811679-e4063f00-9729-11eb-9a9a-ddc97c6e084d.png)

The previous subgraph, https://api.thegraph.com/subgraphs/name/umaprotocol/uma, featured 28 of the addresses in the whitelist events:
![image](https://user-images.githubusercontent.com/16608312/113811778-0e57fc80-972a-11eb-8a27-18ba2bdeadff.png)

Both of these graphs are missing token 0x0f7f961648ae6db43c75663ac7e5414eb79b5704 (XIO Network)--you can confirm this by examining this link to the whitelist contract in etherscan https://etherscan.io/address/0xdbf90434df0b98219f87d112f37d74b1d90758c7#events, where the most recent event shows this token being whitelisted:
![image](https://user-images.githubusercontent.com/16608312/113811912-57a84c00-972a-11eb-92e8-717dd27dbd96.png)

**Comment by AC-FTW** [comment]
Here are a list of the missing token addresses in a graphQL query showing they are missing from the current mainnet contract subgraph:

```
{
  tokens(where: {address_in: [
    "0x261b45d85ccfeabb11f022eba346ee8d1cd488c0", 
    "0xdac17f958d2ee523a2206206994597c13d831ec7", 
    "0x758a43ee2bff8230eeb784879cdcff4828f2544d", 
    "0xbd2f0cd039e0bfcf88901c98c0bfac5ab27566e3", 
    "0x19d97d8fa813ee2f51ad4b4e04ea08baf4dffc28", 
    "0x3832d2f059e55934220881f831be501d180671a7", 
    "0x967da4048cd07ab37855c090aaf366e4ce1b9f48", 
    "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599", 
    "0x0aacfbec6a24756c20d41914f2caba817c0d8521", 
    "0xbb2b8038a1640196fbe3e38816f3e67cba72d940", 
    "0xb4e16d0168e52d35cacd2c6185b44281ec28c9dc", 
    "0xd3d2e2692501a5c9ca623199d38826e513033a17", 
    "0x88d97d199b9ed37c29d846d00d443de980832a22", 
    "0xa117000000f279d81a1d3cc75430faa017fa5a2e", 
    "0x0954906da0bf32d5479e25f46056d22f08464cab", 
    "0x1494ca1f11d487c2bbe4543e90080aeba4ba3c2b", 
    "0x6b3595068778dd592e39a122f4f5a5cf09c90fe2", 
    "0x8798249c2e607446efb7ad49ec89dd1865ff4272", 
    "0x0f7f961648ae6db43c75663ac7e5414eb79b5704"
  ]}) {
    address,
    name,
    symbol
  }
}
```

and the current result ...
![image](https://user-images.githubusercontent.com/16608312/113812340-2aa86900-972b-11eb-86ca-4158eca28fff.png)

Run this same query in the subgraph https://api.thegraph.com/subgraphs/name/umaprotocol/uma and only one of them will be missing.

**Comment by AC-FTW** [comment]
I believe the missing tokens should have indexingAsCollateral set to true when/if they are added to this subgraph (that was set to false in the previous subgraph for many of them).

**Comment by nicholaspai** [comment]
> I believe the missing tokens should have indexingAsCollateral set to true when/if they are added to this subgraph (that was set to false in the previous subgraph for many of them).

Hey AC thanks for bringing this up, the `mainnet-contracts` subgraph is still not completed indexing so these tokens should get added. I'm also going to remove the `isOnWhitelist` field since we're no longer indexing the `AddressWhitelist`

**Comment by AC-FTW** [comment]
> Hey AC thanks for bringing this up, the `mainnet-contracts` subgraph is still not completed indexing so these tokens should get added. I'm also going to remove the `isOnWhitelist` field since we're no longer indexing the `AddressWhitelist`

Will indexingAsCollateral still be used?  (I saw what you meant in _meta->block->number--it's still > 100k blocks away from completely indexed).

**Comment by nicholaspai** [comment]
> > Hey AC thanks for bringing this up, the `mainnet-contracts` subgraph is still not completed indexing so these tokens should get added. I'm also going to remove the `isOnWhitelist` field since we're no longer indexing the `AddressWhitelist`
> 
> Will indexingAsCollateral still be used? (I saw what you meant in _meta->block->number--it's still > 100k blocks away from completely indexed).

Yes, but I'm actually considering removing the `Token` entity entirely. Indexing the `ERC20.Transfer` makes the indexing of the subgraph take ~3-5 days on Mainnet whereas removing this allows the subgraph to index in < 1 day. Do you rely on this entity?

**Comment by nicholaspai** [comment]
> > Hey AC thanks for bringing this up, the `mainnet-contracts` subgraph is still not completed indexing so these tokens should get added. I'm also going to remove the `isOnWhitelist` field since we're no longer indexing the `AddressWhitelist`
> 
> Will indexingAsCollateral still be used? (I saw what you meant in _meta->block->number--it's still > 100k blocks away from completely indexed).

Yes, `indexingAsCollateral` will still be used!

**Comment by AC-FTW** [comment]
On Wed, Apr 7, 2021 at 5:39 PM nicholaspai ***@***.***> wrote:

> Hey AC thanks for bringing this up, the mainnet-contracts subgraph is
> still not completed indexing so these tokens should get added. I'm also
> going to remove the isOnWhitelist field since we're no longer indexing
> the AddressWhitelist
>
> Will indexingAsCollateral still be used? (I saw what you meant in
> _meta->block->number--it's still > 100k blocks away from completely
> indexed).
>
> Yes, but I'm actually considering removing the Token entity entirely.
> Indexing the ERC20.Transfer makes the indexing of the subgraph take ~3-5
> days on Mainnet whereas removing this allows the subgraph to index in < 1
> day. Do you rely on this entity?
>
> —
>
We query the Token entity directly just to populate the name & symbol in
the dashboard's 'Registered Collateral Types' table.  We could
probably source that data elsewhere (etherscan, other graphs, a LUT)--let
us know if you do remove that entity entirely or if you decide to just push
it into its own subgraph.
