### ISSUE TITLE
Tokens filter in Mainnet Contract does not reflect whitelist status.

### ISSUE THREAD

**Issue by AC-FTW** [UMAprotocol/subgraphs#8]
The token UNI (0x1f9840a85d5af5bf1d1762f925bdaddc4201f984) is a whitelisted token--you can see that in Etherscan's logs for UMA's whitelist contract here: https://etherscan.io/tx/0xdcffa6f68ac01dc83da863930bdbf81f1411c8b101fbd8b16cf2dbf9352ba0d3#eventlog
![image](https://user-images.githubusercontent.com/16608312/113814678-3d24a180-972f-11eb-8fde-2878c3058c36.png)

Unfortunately a query of the current mainnet contracts graph does not reflect the whitelist status:
```
{
  tokens(where: {symbol_starts_with: "UNI"}) {
    id
    address
    symbol
    isOnWhitelist
  }
}
```
![image](https://user-images.githubusercontent.com/16608312/113814844-807f1000-972f-11eb-8bff-cee5ede89169.png)

**Comment by nicholaspai** [comment]
I've removed the `AddressWhitelist` entity so this field is going to be deprecated. Do you rely on the list of all whitelisted tokens?

**Comment by AC-FTW** [comment]
> I've removed the `AddressWhitelist` entity so this field is going to be deprecated. Do you rely on the list of all whitelisted tokens?

Thanks for asking.  We're not using that entity in any of the service calls to the graph (we're using the devmining-status.json file in GH to get WL info).
